### PR TITLE
fix: eliminate remaining race conditions

### LINKED ISSUE #169: Data races
fix all data races

### PR DESCRIPTION
**Pull request by steebchen**
# Description

Fixes #169 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## What's Changed

- [x] fix race conditions in engine
- [x] fix e2e test race conditions

### CODE REVIEW

File: internal/logger/stderr.go [hunk 1]
```diff
@@ -15,7 +14,7 @@ func NewDefaultLogger(service string) zerolog.Logger {
 }
 
 func NewStdErr(cf *shared.LoggerConfigFile, service string) zerolog.Logger {
-	zerolog.TimeFieldFormat = time.RFC3339Nano
+	// zerolog.TimeFieldFormat = time.RFC3339Nano
```
Comment (steebchen) [inline internal/logger/stderr.go]: There doesn't seem to be another way to do this but this results in a data race
cc @abelanger5

Comment (abelanger5) [reply internal/logger/stderr.go]: Can't we put this in an `init` method?

**Review by abelanger5 — APPROVED** [review]

File: internal/logger/stderr.go (hunk 1 above)
Comment (steebchen) [reply internal/logger/stderr.go]: yep works, good idea 👍
