### PR TITLE
Fix ts  feature client namespaces

### LINKED ISSUE #1780: [BUG] Namespaces are broken in V1 TS SDK
**Describe the issue**
Namespaces are broken in V1 TS SDK

**Environment**
- SDK: TypeScript v1.6.1
- Engines: Cloud v0 and latest self-hosted hatchet-lite

**Expected behavior**
When defining a namespace `foo` in my Hatchet client, via `const hatchet = Hatchet.init({namespace: 'foo'});`, I expect workflows and workers to consistently be prefixed with `foo_`, as was the case in V0. This is not the case with the V1 SDK. This prevents Hatchet from working, basically.

Suppose for example that:
- I have a workflow named `bar`, which I construct with `const wf = hatchet.workflow({name: 'bar', ... });`,
- I have a worker named `quux`, which I construct with `const wk = await hatchet.worker('quux');`.

In the hatchet dashboard, the worker will show up as `fooquux` instead of the expected `foo_quux`. Furthermore if I `await wk.registerWorkflows([wf])` then the workflow shows up in the dashboard as `foobar` instead of the expected `foo_bar`.

When submitting a workflow run request in another node app via, say, `await hatchet.admin.runWorkflow('bar', ...)` or `await wf.runNoWait(...)` then it gets the namespacing right and tries to run `foo_bar`, which it doesn't find. However if the worker registers the workflow with a horrible hack along the lines of `await wk.registerWorkflows([{...wf, name: "_" + wf.name}])`, then everything works as expected.

I had similar results when setting the namespace via the env var instead.

**Code to Reproduce, Logs, or Screenshots**
What I described above is reproducible using the hatchet-lite docker-compose engine and a very bare bones TS setup.

**Additional context**
This seems to be a bug in the TS SDK because I've been experiencing the same thing in both a local hatchet-lite deployment (via docker compose) and in the cloud v0 engine, which we'd like to upgrade.

### PR DESCRIPTION
**Pull request by grutt**
# Description
Fixes namespaces for scheduled and cron runs

Fixes: #1780

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: sdks/typescript/src/util/with-namespace.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export function withNamespace(name: string, namespace?: string) {
```
Comment (mrkaye97) [inline sdks/typescript/src/util/with-namespace.ts]: nit: I think we should call this the same thing (and maybe match the impl?) that it's called in [Python](https://github.com/hatchet-dev/hatchet/blob/fix--bug-burndown-part-ii/sdks/python/hatchet_sdk/config.py#L157-L171) and [Go](https://github.com/hatchet-dev/hatchet/blob/fix--bug-burndown-part-ii/pkg/config/client/client.go#L85)

Comment (mrkaye97) [reply sdks/typescript/src/util/with-namespace.ts]: Although I guess those impls aren't really the same so 🤦

File: sdks/typescript/src/clients/admin/admin-client.ts [hunk 2]
```diff
@@ -182,9 +183,7 @@ export class AdminClient {
     let computedName = workflowName;
```
Comment (mrkaye97) [inline sdks/typescript/src/clients/admin/admin-client.ts]: I'm kinda surprised the linter is fine with this but alas - I think this should be:

```typescript
const computedName = withNamespace(workflowName, this.config.namespace)
```

?

same in other places too if we can 🤷

File: sdks/typescript/src/clients/worker/worker.ts [hunk 3]
```diff
@@ -121,7 +122,7 @@ export class V0Worker {
     for (const workflow of workflows) {
       const wf: Workflow = {
         ...workflow,
-        id: this.client.config.namespace + workflow.id,
+        id: withNamespace(workflow.id, this.client.config.namespace),
```
Comment (mrkaye97) [inline sdks/typescript/src/clients/worker/worker.ts]: I guess `id` here really means `name`?

File: sdks/typescript/src/clients/worker/worker.ts [hunk 4]
```diff
@@ -144,7 +145,7 @@ export class V0Worker {
   async registerWorkflow(initWorkflow: Workflow) {
     const workflow: Workflow = {
       ...initWorkflow,
-      id: (this.client.config.namespace + initWorkflow.id).toLowerCase(),
+      id: withNamespace(initWorkflow.id, this.client.config.namespace).toLowerCase(),
```
Comment (mrkaye97) [inline sdks/typescript/src/clients/worker/worker.ts]: same here 😅  this is a bit confusing - I guess it'd be a breaking change to fix this maybe? this feels like the kind of thing we'll try to reread in a few months and not understand though

File: sdks/typescript/src/util/config-loader/config-loader.ts [hunk 5]
```diff
@@ -94,7 +97,7 @@ export class ConfigLoader {
         (this.env('HATCHET_CLIENT_LOG_LEVEL') as LogLevel) ??
         'INFO',
       tenant_id: tenantId,
-      namespace: namespace ? `${namespace}_`.toLowerCase() : '',
```
Comment (mrkaye97) [inline sdks/typescript/src/util/config-loader/config-loader.ts:97]: just confirming: was this related to that other bug a few months ago with the missing underscore or double underscore or something?

File: sdks/typescript/src/util/uuid.ts [hunk 6]
```diff
@@ -0,0 +1,10 @@
+export function isValidUUID(uuid: string): boolean {
+  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(uuid);
```
Comment (mrkaye97) [inline sdks/typescript/src/util/uuid.ts]: there must be a way to do this with a library 😅

File: sdks/typescript/src/v1/client/client.ts [hunk 7]
```diff
@@ -91,13 +93,6 @@ export class HatchetClient implements IHatchetClient {
         logger: logConstructor,
       };
 
-      // FIXME: Remove this once we have a proper namespace validation
-      if (clientConfig.namespace) {
-        clientConfig.namespace = clientConfig.namespace.endsWith('_')
-          ? clientConfig.namespace.slice(0, -1)
-          : clientConfig.namespace;
-      }
```
Comment (mrkaye97) [inline sdks/typescript/src/v1/client/client.ts:99]: 🥳

File: sdks/typescript/src/util/with-namespace.ts (hunk 1 above)
Comment (grutt) [reply sdks/typescript/src/util/with-namespace.ts]: matching name is fine

File: sdks/typescript/src/clients/admin/admin-client.ts (hunk 2 above)
Comment (grutt) [reply sdks/typescript/src/clients/admin/admin-client.ts]: yeah weird, resolved regardless good catch

File: sdks/typescript/src/clients/worker/worker.ts (hunk 3 above)
Comment (grutt) [reply sdks/typescript/src/clients/worker/worker.ts]:
```
  /**
   * @deprecated use definition.name instead
   */
  get id() {
    return this.definition.name;
  }
```

yeah... i have this getter for backwards compat. i'll go through and clean this up another day

**Review by mrkaye97 — APPROVED** [review]

File: sdks/typescript/src/clients/worker/worker.ts (hunk 3 above)
Comment (mrkaye97) [reply sdks/typescript/src/clients/worker/worker.ts]: yeah sounds good, not a big deal

File: sdks/typescript/src/util/uuid.ts (hunk 6 above)
Comment (grutt) [reply sdks/typescript/src/util/uuid.ts]: good catch, we already have zod as a dep

File: sdks/typescript/src/util/config-loader/config-loader.ts (hunk 5 above)
Comment (grutt) [reply sdks/typescript/src/util/config-loader/config-loader.ts:97]: yes, added a safer way to handle this above

**Review by mrkaye97 — APPROVED** [review]
🥳
