### PR TITLE
Fix: Static rate limits resetting to zero

### LINKED ISSUE #1834: [BUG] Static rate limits reset their own limits to 0
**Describe the issue**
I'm unable to get static rate limits to work at all. They seem to reset their limit (not their value) to 0 as soon as they're used.

**Environment**
- SDK: Python 1.10.2
- Engine: Cloud
- 
**Expected behavior**
I don't expect the limit to change without a call to `hatchet.rate_limits.put()`

**Code to Reproduce, Logs, or Screenshots**
```python
from hatchet_sdk import Context, EmptyModel, Hatchet
from hatchet_sdk.rate_limit import RateLimit, RateLimitDuration
from pydantic import BaseModel

hatchet = Hatchet(debug=True)

class Input(BaseModel):
    foo: int = 100

workflow = hatchet.workflow(name="test", input_validator=Input)

@workflow.task(rate_limits=[
    RateLimit(
        static_key="rate_limit",
        units="input.foo"
    )
])
async def task(input: Input, ctx: Context):
    print(input)
    return {}

if __name__ == "__main__":
    hatchet.rate_limits.put("rate_limit", 1000, RateLimitDuration.MINUTE)
    worker = hatchet.worker(name="test", workflows=[workflow])
    workflow.run_no_wait(Input())
    worker.start()
```

When I run this, the task gets queued:
Image

And if I look at the Rate Limits section, I see:
Image

If I cancel the task and just run:
```
hatchet.rate_limits.put("rate_limit", 1000, RateLimitDuration.MINUTE)
```

The rate limit goes back up:
Image

But as soon as I run the worker again, it drop back to 0.

What am I doing wrong here?

### PR DESCRIPTION
**Pull request by mrkaye97**
# Description

Fixes an issue where static rate limits reset themselves to zero because we would pass `null` for the `limit` value. Instead, passing a sentinel `-1`, and then checking if the limit value is `>= 0` before upserting

Fixes #1834 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: pkg/v1/task/task.go [hunk 1]
```diff
@@ -130,6 +130,11 @@ func makeContractTaskOpts(t *TaskShared, taskDefaults *create.TaskDefaults) *con
 			LimitValuesExpr: rateLimit.LimitValueExpr,
 		}
 
+		if rateLimit.LimitValueExpr == nil {
+			negOne := "-1"
+			rateLimit.LimitValueExpr = &negOne
+		}
```
Comment (mrkaye97) [inline pkg/v1/task/task.go:136]: @mnafees is this the right place to do this? 😅

**Review by abelanger5 — APPROVED** [review]

**Comment by ameya-taliz** [comment]
@mrkaye97 - this fixed the issue with static rate limits in the cloud version, but in self-hosted, now static rate limits get set to be -1 whenever a rate limit is consumed, causing all tasks to be queued.

**Comment by mrkaye97** [comment]
hi @ameya-taliz - which version of the engine are you running?

**Comment by ameya-taliz** [comment]
Pulled latest image today, which looks like version 2.35.1:
```
hatchet-engine:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-engine:latest
    command: /hatchet/hatchet-engine --config /hatchet/config
    restart: on-failure
    depends_on:
      setup-config:
        condition: service_completed_successfully
      migration:
        condition: service_completed_successfully
    ports:
      - "7077:7070"
    environment:
      DATABASE_URL: "postgres://hatchet:hatchet@postgres:5432/hatchet"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
    volumes:
      - hatchet_certs:/hatchet/certs
      - hatchet_config:/hatchet/config
```

**Comment by mrkaye97** [comment]
ah gotcha - the `latest` tag is very old (months). the most recent tags we've pushed is `v0.74.2`, so pulling that should work!

**Comment by ameya-taliz** [comment]
confirmed that worked - thank you for the quick response! Happy New Year!

**Comment by mrkaye97** [comment]
great! happy new year to you too :)
